import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { ArrowRight, CheckCircle2, Compass, LogIn, LogOut, ShieldCheck, Users } from "lucide-react";
import { Link } from "wouter";

export default function Auth() {
  const { user, loading, isAuthenticated, logout } = useAuth();

  return <div className="auth-page"><div className="auth-art"><div className="auth-orbit orbit-a" /><div className="auth-orbit orbit-b" /><div className="auth-art-copy"><span className="eyebrow light-eyebrow">Gwagwalada Connect</span><h1>Community works better when everyone has a place.</h1><p>Find your people, support local talent, and keep progress visible.</p><div className="auth-trust-list"><span><CheckCircle2 size={15} /> Trusted local profiles</span><span><ShieldCheck size={15} /> Safer community connections</span><span><Users size={15} /> 2,418 active residents</span></div></div></div><main className="auth-card"><Link className="auth-brand" href="/"><span className="brand-mark"><Compass size={21} /></span><span><strong>Gwagwalada</strong><em>Connect</em></span></Link>{isAuthenticated ? <><span className="eyebrow">Your account</span><h2>Welcome back, {user?.name?.split(" ")[0] ?? "neighbour"}.</h2><p className="auth-copy">You’re signed in and ready to connect with your community.</p><div className="auth-account"><div className="auth-account-avatar">{user?.name?.slice(0, 2).toUpperCase() ?? "GC"}</div><div><strong>{user?.name ?? "Community member"}</strong><span>{user?.email ?? "Verified Gwagwalada resident"}</span></div><ShieldCheck size={17} /></div><div className="auth-actions"><Link href="/"><Button>Open my community <ArrowRight size={16} /></Button></Link><Button variant="outline" onClick={async () => { await logout(); toast.success("You’ve been signed out safely."); }} disabled={loading}><LogOut size={16} /> Sign out</Button></div></> : <><span className="eyebrow">Welcome to the neighbourhood</span><h2>Sign in to your community.</h2><p className="auth-copy">Use your secure account to follow residents, send connection requests, message accepted contacts, and take part in GEM projects.</p><div className="auth-benefits"><div><Users size={16} /><span><strong>Meet people nearby</strong><small>Find residents, builders, and businesses.</small></span></div><div><ShieldCheck size={16} /><span><strong>Keep connections trusted</strong><small>Friend requests protect your messages.</small></span></div></div><Button className="auth-primary" onClick={() => startLogin()} disabled={loading}><LogIn size={17} /> Continue with secure sign in <ArrowRight size={15} /></Button><p className="auth-terms">By continuing, you agree to keep Gwagwalada Connect respectful and useful for the community.</p></>}{!isAuthenticated && <Link className="auth-back" href="/"><ArrowRight size={14} /> Continue as a visitor</Link>}</main></div>;
}
