from pathlib import Path
import re

path = Path('/home/ubuntu/gwagwalada-connect/client/src/pages/Home.tsx')
source = path.read_text()
source = re.sub(r'const aerialImage = .*?;\nconst projectImage = .*?;\nconst marketImage = .*?;\nconst classroomImage = .*?;\n\n', '', source, flags=re.S)

replacements = {
"HomeView": r'''function HomeView({ viewerName, posts, onLike, onCompose, onView, onToast }: { viewerName: string; posts: Post[]; onLike: (id: number) => void; onCompose: () => void; onView: (view: View) => void; onToast: (message: string) => void }) {
  return <>
    <section className="welcome-row"><div><span className="eyebrow">{new Date().toLocaleDateString("en-NG", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</span><h1>Good morning, {viewerName} <span>✳</span></h1><p>Here’s what’s moving through Gwagwalada today.</p></div><div className="welcome-actions"><Button variant="outline" onClick={() => onView("gallery")}><ShieldCheck size={16} /> Verify a project</Button><Button onClick={onCompose}><Plus size={17} /> Create post</Button></div></section>
    <section className="signal-grid"><div className="signal-card signal-primary"><div className="signal-top"><div><span className="eyebrow light-eyebrow">Community pulse</span><strong>{posts.length ? "Fresh local updates" : "Your community starts here"}</strong></div><span className="signal-icon"><BarChart3 size={18} /></span></div><div className="signal-number">{posts.length} <small>published updates</small></div><div className="signal-foot"><span><i className="green-dot" /> Live database feed</span><span>{posts.length ? "Active" : "Waiting"}</span></div></div><div className="signal-card"><div className="signal-top"><div><span className="eyebrow">GEM projects</span><strong>Visible progress</strong></div><span className="signal-icon sage-icon"><CheckCircle2 size={18} /></span></div><div className="project-progress"><div><strong>0</strong><span>verified projects</span></div><Progress value={0} /><span className="progress-label">No project updates yet</span></div><button className="card-link" onClick={() => onView("gallery")}>Open project trail <ArrowRight size={14} /></button></div><div className="signal-card"><div className="signal-top"><div><span className="eyebrow">Youth opportunities</span><strong>Find your next move</strong></div><span className="signal-icon blue-icon"><BriefcaseBusiness size={18} /></span></div><div className="opportunity-row"><div className="mini-avatars"><Avatar initials="GC" tone="blue" size="sm" /></div><div><strong>Explore local opportunities</strong><span>Published by community members</span></div></div><button className="card-link" onClick={() => onView("marketplace")}>Open marketplace <ArrowRight size={14} /></button></div></section>
    <div className="content-grid"><section className="feed-column"><div className="section-heading"><div><span className="eyebrow">From your community</span><h2>Community feed</h2></div><button className="filter-button" onClick={() => onToast("Feed filters are coming soon.")}>Latest <ChevronRight size={15} /></button></div><div className="quick-composer" onClick={onCompose}><Avatar initials="GC" tone="peach" /><div>Share something with the community...</div><button onClick={(event) => { event.stopPropagation(); onCompose(); }}><Plus size={17} /></button></div>{posts.length ? posts.map((post) => <PostCard key={post.id} post={post} onLike={onLike} onToast={onToast} />) : <div className="empty-state feed-empty"><Newspaper size={24} /><strong>No updates have been published yet.</strong><p>Be the first neighbour to share something useful with Gwagwalada.</p><Button onClick={onCompose}><Plus size={15} /> Create the first post</Button></div>}</section><aside className="home-rail"><div className="rail-card spotlight-card"><div className="rail-card-header"><div><span className="eyebrow">Community spotlight</span><h3>Stories from<br /><em>your neighbourhood.</em></h3></div><span className="sparkle-badge"><Sparkles size={16} /></span></div><div className="empty-state compact-empty"><Camera size={20} /><p>Community stories will appear here once residents publish updates.</p></div></div><div className="rail-card"><div className="rail-card-header"><div><span className="eyebrow">Quick links</span><h3>Make your mark</h3></div><LayoutGrid size={18} className="muted-icon" /></div><div className="quick-links"><button onClick={() => onView("gallery")}><span className="quick-icon peach-icon"><Camera size={16} /></span><span><strong>Verify a project</strong><small>Add field evidence</small></span><ChevronRight size={15} /></button><button onClick={() => onView("classroom")}><span className="quick-icon blue-icon"><BookOpen size={16} /></span><span><strong>Learn a skill</strong><small>GEM digital classroom</small></span><ChevronRight size={15} /></button><button onClick={() => onView("marketplace")}><span className="quick-icon sage-icon"><Store size={16} /></span><span><strong>Support local</strong><small>Shop the marketplace</small></span><ChevronRight size={15} /></button></div></div></aside></div>
  </>;
}''',
"MarketplaceView": r'''function MarketplaceView({ filter, setFilter, search, setSearch, listings, onToast }: { filter: string; setFilter: (value: string) => void; search: string; setSearch: (value: string) => void; listings: Listing[]; onToast: (message: string) => void }) {
  const filters = ["All", "Tech", "Handwork", "Commerce", "General Labor"];
  return <><section className="page-hero marketplace-hero"><div><span className="eyebrow light-eyebrow">Support local talent</span><h1>Youth marketplace</h1><p>Find something made, grown, or built right here in Gwagwalada.</p></div><div className="hero-stat"><span><Store size={18} /> Published listings</span><strong>{listings.length}</strong><small>Live database results</small></div></section><div className="market-toolbar"><div className="market-search"><Search size={17} /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search goods, services, or sellers" /></div><Button onClick={() => onToast("Listing form opened.")}><Plus size={17} /> List something</Button></div><div className="filter-row">{filters.map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}<span className="filter-result">{listings.length} results</span></div><section className="listing-grid">{listings.length ? listings.map((listing) => <Card className="listing-card" key={listing.id}><div className="listing-image">{listing.image ? <img src={listing.image} alt={listing.title} /> : <div className="listing-image-placeholder"><Store size={26} /><span>No image</span></div>}<span>{listing.category}</span><button onClick={() => onToast("Saved to your items.")}><Heart size={16} /></button></div><div className="listing-copy"><div className="listing-seller"><Avatar initials={listing.seller.slice(0, 2).toUpperCase()} tone={listing.category === "Tech" ? "blue" : "peach"} size="sm" /><span><strong>{listing.seller} {listing.verified && <ShieldCheck size={13} />}</strong><small><MapPin size={12} /> {listing.location ?? "Gwagwalada"} · {listing.rating}</small></span></div><h3>{listing.title}</h3><div className="listing-foot"><strong>{listing.price}</strong><button onClick={() => onToast(`Opening a chat with ${listing.seller}`)}>Message seller <ArrowRight size={14} /></button></div></div></Card>) : <div className="empty-state marketplace-empty"><Store size={25} /><strong>No marketplace listings yet.</strong><p>Publish the first local good or service to start the marketplace.</p><Button onClick={() => onToast("Listing form opened.")}><Plus size={15} /> List something</Button></div>}</section><section className="task-board"><div className="section-heading"><div><span className="eyebrow">Get paid for what you can do</span><h2>Task board</h2></div><button className="card-link" onClick={() => onToast("Task board is empty until a task is published.")}>View all tasks <ArrowRight size={14} /></button></div><div className="empty-state compact-empty"><BriefcaseBusiness size={20} /><p>No community tasks have been published yet.</p></div></section></>;
}''',
"ClassroomView": r'''function ClassroomView({ courses, courseProgress, onStart, onToast }: { courses: Course[]; courseProgress: Record<string, number>; onStart: (course: Course) => void; onToast: (message: string) => void }) {
  return <><section className="page-hero classroom-hero"><div><span className="eyebrow light-eyebrow">Learn. Build. Earn.</span><h1>GEM digital classroom</h1><p>Practical skills, taught for the opportunities already growing around you.</p></div><div className="classroom-hero-art"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><GraduationCap size={54} /></div></section><div className="classroom-stat-row"><div><span className="stat-icon peach-icon"><BookOpen size={18} /></span><div><strong>{courses.length}</strong><small>published courses</small></div></div><div><span className="stat-icon sage-icon"><CheckCircle2 size={18} /></span><div><strong>0</strong><small>certificates earned</small></div></div><div><span className="stat-icon blue-icon"><Clock3 size={18} /></span><div><strong>0h</strong><small>learning time</small></div></div><div className="classroom-stat-cta"><Button variant="outline" onClick={() => onToast("Certificates will appear here after you complete a course.")}><FileText size={16} /> My certificates</Button></div></div><section className="course-section"><div className="section-heading"><div><span className="eyebrow">Keep growing</span><h2>Continue learning</h2></div><button className="filter-button" onClick={() => onToast("Showing your published courses.")}>All courses <ChevronRight size={15} /></button></div>{courses.length ? <div className="course-grid">{courses.map((course) => { const progress = courseProgress[course.title] ?? course.progress; return <Card className="course-card" key={course.title}><div className="course-copy"><h3>{course.title}</h3><p>{course.meta} · {course.learners}</p><div className="course-progress-line"><Progress value={progress} /><span>{progress}%</span></div><button className="course-continue" onClick={() => onStart(course)}>{progress > 0 ? "Continue course" : "Start course"}<ArrowRight size={15} /></button></div></Card>; })}</div> : <div className="empty-state"><GraduationCap size={25} /><strong>No courses published yet.</strong><p>GEM learning content will appear here when the classroom catalog is ready.</p></div>}</section><section className="learning-banner"><div className="learning-banner-copy"><span className="eyebrow">Designed for Gwagwalada</span><h2>Your skill is a community asset.</h2><p>Complete a course, add your certificate to your profile, and get discovered by local businesses looking for exactly what you can do.</p><Button onClick={() => onToast("Skills assessment coming soon.")}>Take the skills assessment <ArrowRight size={15} /></Button></div></section></>;
}''',
"GalleryView": r'''function GalleryView({ onToast }: { onToast: (message: string) => void }) {
  return <><section className="page-hero gallery-hero"><div><span className="eyebrow light-eyebrow">Proof in the open</span><h1>Movement gallery</h1><p>See what’s happening on the ground. Add your own evidence to the story.</p></div><Button onClick={() => onToast("Project verification form opened.")}><Upload size={16} /> Verify a project</Button></section><section className="verification-banner"><div className="verification-icon"><ShieldCheck size={24} /></div><div><span className="eyebrow">Civic project verification</span><h2>Turn claims into a public trail.</h2><p>Upload a field photo, choose your visibility, and help neighbours see what is completed, what is in progress, and what needs attention.</p></div><div className="verification-stats"><div><strong>0</strong><span>projects tracked</span></div><div><strong>0</strong><span>field updates</span></div><div><strong>0</strong><span>areas covered</span></div></div></section><div className="gallery-grid"><div className="gallery-feature gallery-empty"><Camera size={30} /><h2>No community media yet.</h2><p>Verified project photos and movement stories will appear here after residents contribute them.</p><Button onClick={() => onToast("Project verification form opened.")}><Upload size={15} /> Add field evidence</Button></div></div><section className="project-trail"><div className="section-heading"><div><span className="eyebrow">Open accountability</span><h2>Project trail</h2></div><button className="card-link" onClick={() => onToast("No projects have been published yet.")}>See all projects <ArrowRight size={14} /></button></div><div className="empty-state compact-empty"><ShieldCheck size={20} /><p>No civic projects have been published for verification yet.</p></div></section></>;
}''',
"PeopleView": r'''function PeopleView({ people, followedPeople, friendRequests, onFollow, onFriendRequest, onMessage }: { people: Person[]; followedPeople: string[]; friendRequests: Record<string, "none" | "pending" | "accepted">; onFollow: (personId: string, name: string) => void; onFriendRequest: (personId: string, next: "pending" | "accepted", name: string) => void; onMessage: (person: Person) => void }) {
  const [query, setQuery] = useState("");
  const filteredPeople = people.filter((person) => `${person.name} ${person.role} ${person.area}`.toLowerCase().includes(query.toLowerCase()));
  return <><section className="people-hero"><div><span className="eyebrow light-eyebrow">Your community, closer</span><h1>Find your people</h1><p>Discover residents, builders, businesses, and GEM leaders you can learn from or work with.</p></div><div className="people-hero-stat"><Users size={20} /><strong>{people.length}</strong><span>published profiles</span></div></section><div className="people-toolbar"><div className="people-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, role, or area" /></div><div className="people-toolbar-note"><UserCheck size={15} /> Mutual connections help keep this space trusted.</div></div><div className="people-section-heading"><div><span className="eyebrow">People worth knowing</span><h2>{filteredPeople.length} local profiles</h2></div><span className="people-request-note"><UserPlus size={14} /> {Object.values(friendRequests).filter((status) => status === "pending").length} requests waiting</span></div>{filteredPeople.length ? <div className="people-grid">{filteredPeople.map((person) => { const requestState = friendRequests[person.id] ?? "none"; const isFollowing = followedPeople.includes(person.id); return <Card className="person-card" key={person.id}><div className="person-card-top"><Avatar initials={person.initials} tone={person.tone} size="lg" /><button className={`follow-quiet ${isFollowing ? "following" : ""}`} onClick={() => onFollow(person.id, person.name)}>{isFollowing ? <Check size={14} /> : <Plus size={14} />} {isFollowing ? "Following" : "Follow"}</button></div><div className="person-card-copy"><h3>{person.name} <ShieldCheck size={14} /></h3><StatusBadge tone={person.tone}>{person.role}</StatusBadge><span className="person-area"><MapPin size={12} /> {person.area}</span><p>{person.bio}</p><small><Users size={12} /> {person.mutuals} mutual connections</small></div><div className="person-card-actions">{requestState === "accepted" ? <Button onClick={() => onMessage(person)}><MessageCircle size={15} /> Message</Button> : requestState === "pending" ? <Button variant="outline" onClick={() => onFriendRequest(person.id, "accepted", person.name)}><UserCheck size={15} /> Accept request</Button> : <Button variant="outline" onClick={() => onFriendRequest(person.id, "pending", person.name)}><UserPlus size={15} /> Add connection</Button>}<button className="icon-button" onClick={() => toast.info(`Opening ${person.name}'s profile.`)}><ChevronRight size={16} /></button></div></Card>; })}</div> : <div className="empty-state"><UserRoundSearch size={25} /><strong>No public profiles yet.</strong><p>New residents will appear here after they complete onboarding.</p></div>}</>;
}''',
"MessagesView": r'''function MessagesView({ selected, setSelected, draft, setDraft, onSend }: { selected: Thread; setSelected: (thread: Thread) => void; draft: string; setDraft: (value: string) => void; onSend: () => void }) {
  return <><section className="messages-heading"><div><span className="eyebrow">Stay connected</span><h1>Messages</h1><p>Conversations with people building, buying, and learning around you.</p></div><Button onClick={() => toast.info("Connect with a community member before starting a message.")}><Plus size={17} /> New message</Button></section><section className="messages-shell"><div className="thread-list"><div className="thread-search"><Search size={16} /><input placeholder="Search messages" /></div>{threads.length ? threads.map((thread) => <button className={`thread-item ${selected.name === thread.name ? "active" : ""}`} onClick={() => setSelected(thread)} key={thread.name}><Avatar initials={thread.initials} tone={thread.tone} /><span><strong>{thread.name}</strong><small>{thread.preview}</small></span><em>{thread.time}{thread.unread > 0 && <i>{thread.unread}</i>}</em></button>) : <div className="empty-state compact-empty"><MessageCircle size={20} /><p>No conversations yet.</p></div>}</div><div className="conversation"><div className="conversation-header"><Avatar initials={selected.initials} tone={selected.tone} /><div><strong>{selected.name}</strong><span><i className="green-dot" /> Direct messages</span></div><button className="icon-button"><MoreHorizontal size={18} /></button></div><div className="conversation-body"><div className="empty-state"><MessageSquare size={25} /><strong>No messages yet.</strong><p>Connect with another community member to start a conversation.</p></div></div><div className="message-composer"><button className="icon-button"><Plus size={18} /></button><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => event.key === "Enter" && onSend()} placeholder="Write a message..." /><button className="send-button" onClick={onSend}><Send size={17} /></button></div></div></section></>;
}'''
}

for name, replacement in replacements.items():
    pattern = rf'function {name}\b[\s\S]*?(?=\nfunction |\Z)'
    source, count = re.subn(pattern, replacement, source, count=1)
    if count != 1:
        raise SystemExit(f'Could not replace {name}')

path.write_text(source)
